# Generated by Django 5.1.2 on 2024-12-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_faq_feature_remove_service_created_at_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='services/default_service.png', null=True, upload_to='services/'),
        ),
    ]
